apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Optisol Tech Company</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          padding: 20px;
        }
        h1 {
          color: #333;
        }
      </style>
    </head>
    <body>
      <h1>Optisol Tech Company</h1>
      <p>Hey Pradeep : )...</p>
    </body>
    </html>